### ISSUE TITLE
I cannot find "veos-lab-4.16.6m-virtualbox.box"

### ISSUE THREAD

**Issue by sayching** [dravetech/network-tutorials#2]
In the website it shows only only veos-lab-4.16.13m.
So I can not find it.
Please help, thanks you !!

**Comment by dbarrosop** [comment]
you can use any veos image you want. The  exact version shouldn’t be an issue. Just edit the Vagrantfile to match your version.

Let me know if you need more help.

**Comment by sayching** [comment]
Thanks for the help sir! While installing and I use the match version but i
use the command "vagrant up" it showed error such as there is no directory
or file in vEOS-lab-16.6M-virtualbox.box

**Comment by sayching** [comment]
Sorry that I didn't take the picture of it. :(

On 13 February 2018 at 08:53, Education Entertainment <chingsay888@gmail.com

**Comment by dbarrosop** [comment]
Yeah, I will need the error to know what that's about.
